// <auto-generated />
namespace CommunityProject_ProjectUnity.DAL.EntityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModelCHange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelCHange));
        
        string IMigrationMetadata.Id
        {
            get { return "201802200646161_ModelCHange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
